name: Common
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  cwd: ${{github.workspace}}/packages/common

defaults:
  run:
    working-directory: packages/common

jobs:
  test-common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1

      - name: Dependency cache
        uses: actions/cache@v2
        id: cache
        with:
          key: Common-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('../../yarn.lock') }}
          path: '**/node_modules'

      # Installs root dependencies, ignoring Bootstrap All script.
      # Bootstraps the current package only
      - run: npx lerna bootstrap --scope @ethereumjs/common
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{github.workspace}}

      # Builds current package and the ones it depends from.
      - run: yarn run build:common
        working-directory: ${{github.workspace}}

      - run: yarn run coverage

      - uses: codecov/codecov-action@v1
        with:
          file: ${{ env.cwd }}/coverage/lcov.info
          flags: common
        if: ${{ matrix.node-version == 12 }}

      - run: yarn run lint
