name: Node versions
on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  get-node-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/checkout@v2

      - run: cat ${{github.workspace}}/scripts/node_versions.json

      - id: set-matrix
        run: echo "::set-output name=matrix::$(cat ${{github.workspace}}/scripts/node_versions.json)"

  tests:
    needs: get-node-versions
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.get-node-versions.outputs.matrix) }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/checkout@v2

      - run: npm install
      - run: npm run build

      - name: Test Common
        run: npm run test
        working-directory: packages/common

