name: Node versions
on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"node\":[10, 12, 14]}"

  tests:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/checkout@v2

      - run: npm install
      - run: npm run build

      - name: Test Common
        run: npm run test
        working-directory: packages/common

